Nicer error messages (at scripts' starts)

diff --git a/agno_add b/agno_add
--- a/agno_add
+++ b/agno_add
@@ -1,18 +1,21 @@
 #!/bin/sh -e
 
-test -e "$1" || exit 1
+if [ ! -e "$1" ]; then
+	echo "ERROR: Provided package file doesn't exist!"
+	exit 1
+fi
 
 # get our vars
 . $HOME/agno/agnorc || exit 1
 
-PKGFILE=$(basename $1)
+PKGFILE=$(basename "$1")
 PKGNAME=$(echo $PKGFILE | cut -d\# -f1)
 
 # re-define var
 AGNO_WORK=$AGNO_WORK/$PKGFILE
 
 # uninstall package if it already exists
-if [ -n "$(ls -1 $AGNO_META | grep $PKGNAME)" ]; then
+if \ls -1 $AGNO_META | grep -q $PKGNAME; then
 	echo "Deleting previously installed package of same name."
 	$AGNO_HOME/agno_rm $PKGNAME
 fi
diff --git a/agno_mk b/agno_mk
--- a/agno_mk
+++ b/agno_mk
@@ -2,7 +2,12 @@
 
 # load our vars
 . $HOME/agno/agnorc || exit 1
-. ./Pkgfile || exit 1
+if [ ! -e ./Pkgfile ]; then
+	echo "ERROR: There's no Pkgfile in the current dir!"
+	exit 1
+else
+	. ./Pkgfile
+fi
 
 PKGFILE_DIR=$PWD
 
