agnoadd and agnomk got some niceties
agnomk:
Now checks if file exists before trying to download it, if it does exist
then it skips the download and informs the user.

agnoadd:
Checks if provided package file exists, exits if it doesn't.

It also checks if the file is installed (i.e. can be found in
$AGNO_META), if it is installed then it first uninstalls it and then
installs it again.

bootstrap.sh:
ln -s -> ln -sf.  I just figured out that the commands I had under
usr/bin/ weren't symlinks, but rather copies of the original files (for
whatever reason), so the last commits I wasn't actually testing.  I did
this in order to make sure the symlinking actually does something.

diff --git a/agno_add b/agno_add
--- a/agno_add
+++ b/agno_add
@@ -1,18 +1,34 @@
 #!/bin/sh -e
 
+test -e "$1" || exit 1
+
 # get our vars
 . $HOME/agno/agnorc || exit 1
 
-PKGFILE="$(basename $1)"
-PKGNAME="$(echo $PKGFILE | cut -d# -f1)"
+PKGFILE=$(basename $1)
+PKGNAME=$(echo $PKGFILE | cut -d\# -f1)
+
+# re-define var
+AGNO_WORK=$AGNO_WORK/$PKGFILE
+
+# uninstall package if it already exists
+if [ -n "$(ls -1 $AGNO_META | grep $PKGNAME)" ]; then
+	echo "Deleting previously installed package of same name."
+	$AGNO_HOME/agno_rm $PKGNAME
+fi
 
 # untar package so we can work with files
+rm -rf $AGNO_WORK
 mkdir -p $AGNO_WORK
 cp "$1" "$AGNO_WORK"
 cd $AGNO_WORK
 tar xzvf $PKGFILE
 
 # copy usr dir, which should contain everything
+if [ ! -d usr ]; then
+	echo "ERROR: There is no usr/ dir in package."
+	exit 1
+fi
 rsync -av usr/ $AGNO_USR
 
 # fill meta data about new package
